export const Admin_Route = '/admin'
export const Login_Route = '/login'
export const Registration_Route = '/registration'
export const Shop_Route = '/shop'
export const Basket_Route = '/basket'
export const Device_Route = '/device'